interface StockSymbol {
  symbol: string;
  name: string;
  exchange: 'NYSE' | 'NASDAQ';
}

// Top NYSE stocks (S&P 500 components and major market cap)
export const NYSE_SYMBOLS: StockSymbol[] = [
  { symbol: 'JPM', name: 'JPMorgan Chase', exchange: 'NYSE' },
  { symbol: 'V', name: 'Visa Inc', exchange: 'NYSE' },
  { symbol: 'JNJ', name: 'Johnson & Johnson', exchange: 'NYSE' },
  { symbol: 'WMT', name: 'Walmart', exchange: 'NYSE' },
  { symbol: 'PG', name: 'Procter & Gamble', exchange: 'NYSE' },
  { symbol: 'MA', name: 'Mastercard', exchange: 'NYSE' },
  { symbol: 'UNH', name: 'UnitedHealth', exchange: 'NYSE' },
  { symbol: 'HD', name: 'Home Depot', exchange: 'NYSE' },
  { symbol: 'BAC', name: 'Bank of America', exchange: 'NYSE' },
  { symbol: 'DIS', name: 'Walt Disney', exchange: 'NYSE' },
  { symbol: 'KO', name: 'Coca-Cola', exchange: 'NYSE' },
  { symbol: 'PFE', name: 'Pfizer', exchange: 'NYSE' },
  { symbol: 'VZ', name: 'Verizon', exchange: 'NYSE' },
  { symbol: 'MRK', name: 'Merck', exchange: 'NYSE' },
  { symbol: 'CVX', name: 'Chevron', exchange: 'NYSE' },
  { symbol: 'XOM', name: 'Exxon Mobil', exchange: 'NYSE' },
  { symbol: 'ABT', name: 'Abbott Labs', exchange: 'NYSE' },
  { symbol: 'CRM', name: 'Salesforce', exchange: 'NYSE' },
  { symbol: 'ORCL', name: 'Oracle', exchange: 'NYSE' },
  { symbol: 'NKE', name: 'Nike', exchange: 'NYSE' },
  { symbol: 'T', name: 'AT&T', exchange: 'NYSE' },
  { symbol: 'WFC', name: 'Wells Fargo', exchange: 'NYSE' },
  { symbol: 'C', name: 'Citigroup', exchange: 'NYSE' },
  { symbol: 'GS', name: 'Goldman Sachs', exchange: 'NYSE' },
  { symbol: 'IBM', name: 'IBM', exchange: 'NYSE' },
  { symbol: 'LLY', name: 'Eli Lilly', exchange: 'NYSE' },
  { symbol: 'BRK-B', name: 'Berkshire Hathaway', exchange: 'NYSE' },
  { symbol: 'TMO', name: 'Thermo Fisher', exchange: 'NYSE' },
  { symbol: 'ABBV', name: 'AbbVie', exchange: 'NYSE' },
  { symbol: 'DHR', name: 'Danaher', exchange: 'NYSE' },
  { symbol: 'LMT', name: 'Lockheed Martin', exchange: 'NYSE' },
  { symbol: 'RTX', name: 'RTX Corporation', exchange: 'NYSE' },
  { symbol: 'BMY', name: 'Bristol-Myers Squibb', exchange: 'NYSE' },
  { symbol: 'SPGI', name: 'S&P Global', exchange: 'NYSE' },
  { symbol: 'CAT', name: 'Caterpillar', exchange: 'NYSE' },
  { symbol: 'DE', name: 'John Deere', exchange: 'NYSE' },
  { symbol: 'MMM', name: '3M Company', exchange: 'NYSE' },
  { symbol: 'GE', name: 'General Electric', exchange: 'NYSE' },
  { symbol: 'HON', name: 'Honeywell', exchange: 'NYSE' },
  { symbol: 'UPS', name: 'United Parcel Service', exchange: 'NYSE' },
  { symbol: 'LOW', name: 'Lowes', exchange: 'NYSE' },
  { symbol: 'TGT', name: 'Target', exchange: 'NYSE' },
  { symbol: 'MDT', name: 'Medtronic', exchange: 'NYSE' },
  { symbol: 'BLK', name: 'BlackRock', exchange: 'NYSE' },
  { symbol: 'SCHW', name: 'Charles Schwab', exchange: 'NYSE' },
  { symbol: 'AXP', name: 'American Express', exchange: 'NYSE' },
  { symbol: 'MS', name: 'Morgan Stanley', exchange: 'NYSE' },
  { symbol: 'USB', name: 'U.S. Bancorp', exchange: 'NYSE' },
  { symbol: 'PNC', name: 'PNC Financial', exchange: 'NYSE' },
  { symbol: 'TFC', name: 'Truist Financial', exchange: 'NYSE' },
  { symbol: 'COP', name: 'ConocoPhillips', exchange: 'NYSE' },
  { symbol: 'SLB', name: 'Schlumberger', exchange: 'NYSE' },
  { symbol: 'EOG', name: 'EOG Resources', exchange: 'NYSE' },
  { symbol: 'MPC', name: 'Marathon Petroleum', exchange: 'NYSE' },
  { symbol: 'PSX', name: 'Phillips 66', exchange: 'NYSE' },
  { symbol: 'VLO', name: 'Valero Energy', exchange: 'NYSE' },
  { symbol: 'SO', name: 'Southern Company', exchange: 'NYSE' },
  { symbol: 'DUK', name: 'Duke Energy', exchange: 'NYSE' },
  { symbol: 'NEE', name: 'NextEra Energy', exchange: 'NYSE' },
  { symbol: 'D', name: 'Dominion Energy', exchange: 'NYSE' },
  { symbol: 'SRE', name: 'Sempra Energy', exchange: 'NYSE' },
  { symbol: 'AEP', name: 'American Electric Power', exchange: 'NYSE' },
  { symbol: 'EXC', name: 'Exelon', exchange: 'NYSE' },
  { symbol: 'XEL', name: 'Xcel Energy', exchange: 'NYSE' },
  { symbol: 'WM', name: 'Waste Management', exchange: 'NYSE' },
  { symbol: 'RSG', name: 'Republic Services', exchange: 'NYSE' },
  { symbol: 'AMT', name: 'American Tower', exchange: 'NYSE' },
  { symbol: 'CCI', name: 'Crown Castle', exchange: 'NYSE' },
  { symbol: 'PLD', name: 'Prologis', exchange: 'NYSE' },
  { symbol: 'EQIX', name: 'Equinix', exchange: 'NYSE' },
  { symbol: 'SPG', name: 'Simon Property Group', exchange: 'NYSE' },
  { symbol: 'O', name: 'Realty Income', exchange: 'NYSE' },
  { symbol: 'WELL', name: 'Welltower', exchange: 'NYSE' },
  { symbol: 'AVB', name: 'AvalonBay Communities', exchange: 'NYSE' },
  { symbol: 'EQR', name: 'Equity Residential', exchange: 'NYSE' },
];

// Top NASDAQ stocks (Tech-heavy, S&P 500 components)
export const NASDAQ_SYMBOLS: StockSymbol[] = [
  { symbol: 'AAPL', name: 'Apple', exchange: 'NASDAQ' },
  { symbol: 'MSFT', name: 'Microsoft', exchange: 'NASDAQ' },
  { symbol: 'GOOGL', name: 'Alphabet (Google)', exchange: 'NASDAQ' },
  { symbol: 'AMZN', name: 'Amazon', exchange: 'NASDAQ' },
  { symbol: 'NVDA', name: 'NVIDIA', exchange: 'NASDAQ' },
  { symbol: 'META', name: 'Meta (Facebook)', exchange: 'NASDAQ' },
  { symbol: 'TSLA', name: 'Tesla', exchange: 'NASDAQ' },
  { symbol: 'AVGO', name: 'Broadcom', exchange: 'NASDAQ' },
  { symbol: 'COST', name: 'Costco', exchange: 'NASDAQ' },
  { symbol: 'PEP', name: 'PepsiCo', exchange: 'NASDAQ' },
  { symbol: 'ADBE', name: 'Adobe', exchange: 'NASDAQ' },
  { symbol: 'CSCO', name: 'Cisco', exchange: 'NASDAQ' },
  { symbol: 'NFLX', name: 'Netflix', exchange: 'NASDAQ' },
  { symbol: 'AMD', name: 'AMD', exchange: 'NASDAQ' },
  { symbol: 'INTC', name: 'Intel', exchange: 'NASDAQ' },
  { symbol: 'CMCSA', name: 'Comcast', exchange: 'NASDAQ' },
  { symbol: 'INTU', name: 'Intuit', exchange: 'NASDAQ' },
  { symbol: 'QCOM', name: 'Qualcomm', exchange: 'NASDAQ' },
  { symbol: 'TXN', name: 'Texas Instruments', exchange: 'NASDAQ' },
  { symbol: 'AMGN', name: 'Amgen', exchange: 'NASDAQ' },
  { symbol: 'SBUX', name: 'Starbucks', exchange: 'NASDAQ' },
  { symbol: 'GILD', name: 'Gilead Sciences', exchange: 'NASDAQ' },
  { symbol: 'MDLZ', name: 'Mondelez', exchange: 'NASDAQ' },
  { symbol: 'PYPL', name: 'PayPal', exchange: 'NASDAQ' },
  { symbol: 'BKNG', name: 'Booking Holdings', exchange: 'NASDAQ' },
  { symbol: 'ISRG', name: 'Intuitive Surgical', exchange: 'NASDAQ' },
  { symbol: 'VRTX', name: 'Vertex Pharmaceuticals', exchange: 'NASDAQ' },
  { symbol: 'REGN', name: 'Regeneron', exchange: 'NASDAQ' },
  { symbol: 'ADP', name: 'Automatic Data Processing', exchange: 'NASDAQ' },
  { symbol: 'FISV', name: 'Fiserv', exchange: 'NASDAQ' },
  { symbol: 'ATVI', name: 'Activision Blizzard', exchange: 'NASDAQ' },
  { symbol: 'MU', name: 'Micron Technology', exchange: 'NASDAQ' },
  { symbol: 'LRCX', name: 'Lam Research', exchange: 'NASDAQ' },
  { symbol: 'KLAC', name: 'KLA Corporation', exchange: 'NASDAQ' },
  { symbol: 'AMAT', name: 'Applied Materials', exchange: 'NASDAQ' },
  { symbol: 'SNPS', name: 'Synopsys', exchange: 'NASDAQ' },
  { symbol: 'CDNS', name: 'Cadence Design', exchange: 'NASDAQ' },
  { symbol: 'MRVL', name: 'Marvell Technology', exchange: 'NASDAQ' },
  { symbol: 'ADI', name: 'Analog Devices', exchange: 'NASDAQ' },
  { symbol: 'NXPI', name: 'NXP Semiconductors', exchange: 'NASDAQ' },
  { symbol: 'MCHP', name: 'Microchip Technology', exchange: 'NASDAQ' },
  { symbol: 'ON', name: 'ON Semiconductor', exchange: 'NASDAQ' },
  { symbol: 'FTNT', name: 'Fortinet', exchange: 'NASDAQ' },
  { symbol: 'PANW', name: 'Palo Alto Networks', exchange: 'NASDAQ' },
  { symbol: 'CRWD', name: 'CrowdStrike', exchange: 'NASDAQ' },
  { symbol: 'ZS', name: 'Zscaler', exchange: 'NASDAQ' },
  { symbol: 'DDOG', name: 'Datadog', exchange: 'NASDAQ' },
  { symbol: 'SNOW', name: 'Snowflake', exchange: 'NASDAQ' },
  { symbol: 'TEAM', name: 'Atlassian', exchange: 'NASDAQ' },
  { symbol: 'WDAY', name: 'Workday', exchange: 'NASDAQ' },
  { symbol: 'ZM', name: 'Zoom Video', exchange: 'NASDAQ' },
  { symbol: 'DOCU', name: 'DocuSign', exchange: 'NASDAQ' },
  { symbol: 'OKTA', name: 'Okta', exchange: 'NASDAQ' },
  { symbol: 'SPLK', name: 'Splunk', exchange: 'NASDAQ' },
  { symbol: 'VEEV', name: 'Veeva Systems', exchange: 'NASDAQ' },
  { symbol: 'IDXX', name: 'IDEXX Laboratories', exchange: 'NASDAQ' },
  { symbol: 'ILMN', name: 'Illumina', exchange: 'NASDAQ' },
  { symbol: 'DXCM', name: 'DexCom', exchange: 'NASDAQ' },
  { symbol: 'BIIB', name: 'Biogen', exchange: 'NASDAQ' },
  { symbol: 'MRNA', name: 'Moderna', exchange: 'NASDAQ' },
  { symbol: 'EXA', name: 'Exact Sciences', exchange: 'NASDAQ' },
  { symbol: 'ALGN', name: 'Align Technology', exchange: 'NASDAQ' },
  { symbol: 'HOLX', name: 'Hologic', exchange: 'NASDAQ' },
  { symbol: 'MAR', name: 'Marriott International', exchange: 'NASDAQ' },
  { symbol: 'ABNB', name: 'Airbnb', exchange: 'NASDAQ' },
  { symbol: 'EXPE', name: 'Expedia', exchange: 'NASDAQ' },
  { symbol: 'TCOM', name: 'Trip.com', exchange: 'NASDAQ' },
  { symbol: 'ROST', name: 'Ross Stores', exchange: 'NASDAQ' },
  { symbol: 'DLTR', name: 'Dollar Tree', exchange: 'NASDAQ' },
  { symbol: 'ORLY', name: "O'Reilly Automotive", exchange: 'NASDAQ' },
  { symbol: 'AZO', name: 'AutoZone', exchange: 'NASDAQ' },
  { symbol: 'EBAY', name: 'eBay', exchange: 'NASDAQ' },
  { symbol: 'MELI', name: 'MercadoLibre', exchange: 'NASDAQ' },
  { symbol: 'JD', name: 'JD.com', exchange: 'NASDAQ' },
  { symbol: 'PDD', name: 'PDD Holdings', exchange: 'NASDAQ' },
];

export const ALL_SYMBOLS: StockSymbol[] = [...NYSE_SYMBOLS, ...NASDAQ_SYMBOLS];

export function getSymbolsByExchange(exchanges: ('NYSE' | 'NASDAQ')[]): StockSymbol[] {
  return ALL_SYMBOLS.filter(stock => exchanges.includes(stock.exchange));
}
